/** Common countries for the DPP "Manufacturer country" field - EU member
 * states plus major manufacturing/trading countries. Not the full ISO-3166
 * list; extend as needed. */
export const COUNTRY_OPTIONS: string[] = [
  "Austria",
  "Belgium",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Ireland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Netherlands",
  "Poland",
  "Portugal",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "United Kingdom",
  "Norway",
  "Switzerland",
  "Iceland",
  "Turkey",
  "United States",
  "Canada",
  "Mexico",
  "Brazil",
  "China",
  "Japan",
  "South Korea",
  "Taiwan",
  "India",
  "Vietnam",
  "Thailand",
  "Indonesia",
  "Malaysia",
  "Philippines",
  "Bangladesh",
  "Pakistan",
  "Sri Lanka",
  "Cambodia",
  "Australia",
  "New Zealand",
  "South Africa",
  "Egypt",
  "Morocco",
  "Tunisia",
  "United Arab Emirates",
  "Saudi Arabia",
  "Israel",
  "Russia",
  "Ukraine",
  "Other",
];
